seed: 0

contrastive_sampling:
  M: 10
  N: 100

designs:
  d: null
  # d_data_path: ${${designs.d} if ${designs.d} is not None else 'null'}
  xi: 0.

param_shapes:
  theta_shape: 2
  event_dim: 1

flow_params:
  num_layers: 5
  mlp_num_layers: 4
  mlp_hidden_size: 128
  num_bins: 4

optimization_params:
  learning_rate: 1e-4
  training_steps: 100
  lambda_: 0.99

lagrange_weight_sch:
  use:
  decay: False
  sigmoid: False
  # name: ${'decay' if lagrange_weight_sch.decay else 'sigmoid' if lagrange_weight_sch.sigmoid else 'None'}
  sigmoid_params:
    slope: 10.

hydra:
  run:
    # TODO: Check that xi dimensionality is preserved
    dir: ./data/${designs.d}/${designs.xi}/${optimization_params.lambda_}/${lagrange_weight_sch.sigmoid_params.slope}/${contrastive_sampling.N}/${contrastive_sampling.M}/${now:%Y.%m.%d.%H.%M}
    # ${'null' if not designs.d else designs.d}/${designs.xi}/${optimization_params.lambda_}/${lagrange_weight_sch.sigmoid_params.slope}/${contrastive_sampling.N}/${contrastive_sampling.M}/${now:%Y.%m.%d.%H.%M}
    # subdir: ${hydra.job.num}/${seed}



# hydra:
#   run:
#     # TODO: Check that xi dimensionality is preserved
#     dir: ./data/${'null' if not ${designs.d} else ${designs.d}}/${designs.xi}/${optimization_params.lambda_}/${lagrange_weight_sch.name}/${lagrange_weight_sch.sigmoid_params.slope}/${contrastive_sampling.N}/${contrastive_sampling.M}/${now:%Y.%m.%d.%H.%M}
#     subdir: ${hydra.job.num}/${seed}
