defaults:
  - override hydra/sweeper: nevergrad

version: '0.0.1'

seed: 0

wandb:
  entity: vz_uci
  project: lfiax_lf-pce

contrastive_sampling:
  M: 10
  N: 10

designs:
  d: null
  # d_data_path: ${${designs.d} if ${designs.d} is not None else 'null'}
  xi: 0.

param_shapes:
  theta_shape: 2
  event_dim: 1

flow_params:
  num_layers: 5
  mlp_num_layers: 4
  mlp_hidden_size: 128
  num_bins: 4

optimization_params:
  learning_rate: 1e-3
  xi_learning_rate: 1e-2
  training_steps: 1000
  lambda_: 0.99

lagrange_weight_sch:
  use:
  decay: True
  sigmoid: False
  # name: ${'decay' if lagrange_weight_sch.decay else 'sigmoid' if lagrange_weight_sch.sigmoid else 'None'}
  sigmoid_params:
    slope: 10.

hydra:
  # run:
  sweep:
    # TODO: Check that xi dimensionality is preserved
    dir: ./data/${version}
    # ${'null' if not designs.d else designs.d}/${designs.xi}/${optimization_params.lambda_}/${lagrange_weight_sch.sigmoid_params.slope}/${contrastive_sampling.N}/${contrastive_sampling.M}/${now:%Y.%m.%d.%H.%M}
    # subdir: ${hydra.job.num}/${seed}
    subdir: ${hydra.job.override_dirname}
  sweeper:
    optim:
      optimizer: RandomSearch
      budget: 5
      num_workers: 5
    parametrization:
      contrastive_sampling.M:
        lower: 10
        upper: 15
        integer: true
      contrastive_sampling.N:
        lower: 98
        upper: 102
        integer: true


