defaults:
  - override hydra/launcher: submitit_slurm
  - override hydra/sweeper: nevergrad

version: '0.0.1'

seed: 0

wandb:
  entity: vz_uci
  project: lfiax_lf-pce

contrastive_sampling:
  M: 10
  N: 10

designs:
  d: null
  # d_data_path: ${${designs.d} if ${designs.d} is not None else 'null'}
  xi: 0.

param_shapes:
  theta_shape: 2
  event_dim: 1

flow_params:
  num_layers: 5
  mlp_num_layers: 4
  mlp_hidden_size: 128
  num_bins: 4

optimization_params:
  learning_rate: 1e-3
  xi_learning_rate: 1e-3
  training_steps: 10000
  lambda_: 0.99

lagrange_weight_sch:
  use:
  decay: True
  sigmoid: False
  # name: ${'decay' if lagrange_weight_sch.decay else 'sigmoid' if lagrange_weight_sch.sigmoid else 'None'}
  sigmoid_params:
    slope: 10.

hydra:
  # run:
  sweep:
    # TODO: Check that xi dimensionality is preserved
    dir: ./data/${version}
    # ${'null' if not designs.d else designs.d}/${designs.xi}/${optimization_params.lambda_}/${lagrange_weight_sch.sigmoid_params.slope}/${contrastive_sampling.N}/${contrastive_sampling.M}/${now:%Y.%m.%d.%H.%M}
    # subdir: ${hydra.job.num}/${seed}
    subdir: ${hydra.job.override_dirname}
  launcher:
    max_num_timeout: 10
    timeout_min: 4
    partition: free
    account: eehui_lab
    # nodes: 1
    # array_parallelism: 5
    # ntasks: 1
    # cpus-per-task: 1
    # array: "1:5"
    # mail-type: "fail, end"
    # mail-user: "vzaballa@uci.edu"
    # comment: ICML
    # mem_gb: 64
    # gpus_per_node: 1
  sweeper:
    optim:
      optimizer: RandomSearch
      budget: 4
      num_workers: 4
    parametrization:
      contrastive_sampling.M: [10, 50, 100]
      contrastive_sampling.N: [10, 50, 100]
      optimization_params.learning_rate: [1e-1, 1e-2, 1e-3, 1e-4]
      optimization_params.xi_learning_rate: [1e-1, 1e-2, 1e-3, 1e-4]

